// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8h-6ffPSQmB7VEZLnGvHR1lJc-1u8x80',
    appId: '1:431719915398:android:02c68874b96112f2b01607',
    messagingSenderId: '431719915398',
    projectId: 'studyco-app-55a76',
    storageBucket: 'studyco-app-55a76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-aQJ39ewIdO7U82fzCKRlB0GYcaoaO8',
    appId: '1:431719915398:ios:17f2c30b7781bf9bb01607',
    messagingSenderId: '431719915398',
    projectId: 'studyco-app-55a76',
    storageBucket: 'studyco-app-55a76.firebasestorage.app',
    iosBundleId: 'com.studyco.app.studycoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6yUWy9fRl2RreaeOjNkTKbbw3jCtxUDI',
    appId: '1:431719915398:web:f651ce7a5a0329dfb01607',
    messagingSenderId: '431719915398',
    projectId: 'studyco-app-55a76',
    authDomain: 'studyco-app-55a76.firebaseapp.com',
    storageBucket: 'studyco-app-55a76.firebasestorage.app',
    measurementId: 'G-Q1KKSH1Y8R',
  );
}
